apiVersion: v2
name: quickstarts-manager-chart
description: A Helm chart for deploying the RHOAI Quickstarts Manager plugin
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - rhoai
  - openshift-ai
  - plugin
  - quickstarts-manager
home: https://github.com/rh-ai-community-plugins/quickstarts-manager
sources:
  - https://github.com/rh-ai-community-plugins/quickstarts-manager
