{{- if and .Values.bff.enabled (or .Values.bff.githubToken .Values.bff.proxyUrl) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quickstarts-manager.fullname" . }}-settings
  namespace: {{ include "quickstarts-manager.namespace" . }}
  labels:
    {{- include "quickstarts-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: bff
type: Opaque
data:
  {{- if .Values.bff.githubToken }}
  github-token: {{ .Values.bff.githubToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.bff.proxyUrl }}
  proxy-url: {{ .Values.bff.proxyUrl | b64enc | quote }}
  {{- end }}
{{- end }}
