{{- if and .Values.bff.enabled .Values.bff.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quickstarts-manager.bffServiceAccountName" . }}
  namespace: {{ include "quickstarts-manager.namespace" . }}
  labels:
    {{- include "quickstarts-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: bff
  {{- with .Values.bff.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
