ARG BASE_IMAGE="registry.access.redhat.com/ubi9/nodejs-22:latest"

# Build stage
FROM ${BASE_IMAGE} AS builder

COPY --chown=default:root package*.json ./
RUN npm ci

COPY --chown=default:root . .
RUN npm run build

# Production stage
FROM ${BASE_IMAGE}

COPY --from=builder --chown=1001:0 /opt/app-root/src/dist ./dist
COPY --from=builder --chown=1001:0 /opt/app-root/src/node_modules ./node_modules
COPY --from=builder --chown=1001:0 /opt/app-root/src/package.json ./

EXPOSE 3000

USER 1001:0

CMD ["node", "dist/server.js"]
